version: "3.4"
services:
  webapi:
    image: webapi
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=db;Database=Events;User Id=sa;
      Password=Password123456789;MultipleActiveResultSets=true; 
      TrustServerCertificate=true"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=https://+:443;http://+:80"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Password123456789"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "7095:443"
      - "5058:80"
    depends_on:
      - db
    restart: on-failure
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    platform: linux/amd64
    environment:
      - "SA_PASSWORD=Password123456789"
      - "ACCEPT_EULA=Y"
    volumes:
      - SQL_Server:/var/opt/mssql
    ports:
      - "1433:1433"
  seq:
    image: datalust/seq
    container_name: seqLog
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://seq.example.com
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH
      - =QC6JjaaluxWsBNnBUuV1oN6YByiFaLBHEeTI8jAXrPFBJxbQVODQ8doCAm
      - +ju1JZKhJzyUoZObkqcWOw4td+oBBmOhoNvSGkgCH7vYbgvTEF #Password123456789
    volumes:
      - Seq:/data
    ports:
      - "8081:80"
      - "5342:5341"
volumes:
  SQL_Server: { }
  Seq: { }
