# fly.toml app configuration file generated for events-harbour on 2024-03-24T14:25:30+10:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'events-harbour'
primary_region = 'syd'

[build]
  image = 'arandomname/events-website:latest'

[env]
ASPNETCORE_URLS="http://+:8080"
Cloudinary__CloudName="dxwtrnpqi"
Cloudinary__ApiKey="716378532247242"

[experimental]
allowed_public_ports = []
auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
