# fly.toml app configuration file generated for events-harbor on 2024-04-30T19:06:34+09:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'events-harbor'
primary_region = 'syd'

[build]
  image = 'arandomname/events-website:latest'

[env]
ASPNETCORE_URLS = 'http://+:8080'
Cloudinary__ApiKey = '722555612845155'
Cloudinary__CloudName = 'dxwtrnpqi'

[experimental]
auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
